require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.6'
prepare_react_native_project!

target 'VibesExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  # VibesPush from git (CocoaPods trunk may not have this version)
  pod 'VibesPush', :git => 'https://github.com/vibes/push-sdk-ios.git', :tag => '5.0.1'

  pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Xcode 16+/26: Apple clang enables consteval but fmt's consteval path is broken.
    # -DFMT_USE_CONSTEVAL=0 is overridden by fmt/base.h, so patch the header.
    fmt_base = File.join(__dir__, 'Pods/fmt/include/fmt/base.h')
    if File.exist?(fmt_base)
      File.chmod(0o644, fmt_base)
      contents = File.read(fmt_base)
      patched = contents.gsub(
        /#elif defined\(__cpp_consteval\)\n#  define FMT_USE_CONSTEVAL 1/,
        "#elif defined(__cpp_consteval)\n#  define FMT_USE_CONSTEVAL 0 // patched for Apple clang"
      )
      File.write(fmt_base, patched) if patched != contents
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = [
          min_ios_version_supported.to_f,
          15.6
        ].max.to_s
        build_config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      end
      case target.name
      when 'RCT-Folly'
        target.build_configurations.each do |build_config|
          build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
      end
    end
  end
end
