default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "ios/VibesExample.xcodeproj"
    )

    build_app(
      workspace: "ios/VibesExample.xcworkspace",
      scheme: "VibesExample",
      export_method: "ad-hoc",
      output_directory: "./build",
      output_name: "VibesExample.ipa"
    )

    upload_to_testflight(
      uses_non_exempt_encryption: false
    )
  end
end

platform :android do
  desc "Push a new beta build to Google Play internal track"
  lane :beta do
    gradle(
      project_dir: "android",
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: "internal",
      aab: lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
