# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Firebase"
  lane :beta do
    build_number = ENV['BITRISE_GIT_TAG']
    version_code = ENV['BUNDLE_VERSION']
    version_name = ENV['BUNDLE_VERSION_SHORT_STRING']
    android_set_version_name(
      version_name: version_name,
      gradle_file: "app/build.gradle"
    ) if build_number
    android_set_version_code(
      version_code: version_code, 
      gradle_file: "app/build.gradle" 
    ) if build_number

    gradle(task: "clean assembleRelease")

    firebase_app_distribution(
      app: ENV['FIREBASE_ANDROID_APPID'],
      firebase_cli_token: ENV['FIREBASE_TOKEN'],
      groups: "android-testers",
  )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
